### ISSUE TITLE
OSGi bundle

### ISSUE THREAD

**Issue by GoogleCodeExporter** [unlockha/beanio#26]
```
Hi

At Apache Camel we are added a new camel-beanio component.
https://issues.apache.org/jira/browse/CAMEL-4964

And as we also support OSGi with Camel, it would be nice, if beanio was OSGi 
compliant out of the box.
If you want help how to make your JAR osgi compliant, then let us know, as we 
can help with that.

And thanks for this great library. Its great that you guys take up this task, 
and have an active maintained project, to allow people to parse their CSV, 
fixed length, and whatnot files.

```

Original issue reported on code.google.com by `claus.ib...@gmail.com` on 5 Feb 2012 at 11:18

**Comment by GoogleCodeExporter** [comment]
```
Hi Claus,

If I understand correctly, I will need to do the following to make the library 
OSGI compliant:

1.  Add the appropriate OSGI headers to the JAR manifest.
2.  Allow a ClassLoader to be specified when initiating the framework.

First, am I missing any other steps?  Do I need to implement a BundleActivator?

And second, #2 is planned for release 2.0 (currently under development) using a 
new method StreamFactory.newInstance(ClassLoader cl).  Without this, is there 
any sense in doing #1 in a 1.2.x release?

Any "how to" help you can provide would be appreciated.

Thanks,
Kevin





```

Original comment by `kevin.s...@gmail.com` on 6 Feb 2012 at 1:02
- Changed state: **Accepted**
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Ad 1.
Yeah as you use ANT you can possible do something alike what they do with 
zookeeper project, in the ANT build file.
https://svn.apache.org/repos/asf/zookeeper/trunk/build.xml

As your library do not use any 3rd party JAR files then you do not really need 
to import anything. The export is about the public *packages* you want end 
users of your library to see. So if you have any internal packages then you 
should not export them. If you are in doubt then you can just export all your 
packages.

Ad 2.
Yes that is always good to allow end users to provide a ClassLoader, its not 
only OSGi environments that can be tricky. Also JEE servers and whatnot may 
have classloading issues.

However for Camel we use the method that accepts an InputStream, to load the 
mapping xml file. I assume this would be fine for now in the 1.2.x releases.
```

Original comment by `claus.ib...@gmail.com` on 6 Feb 2012 at 5:19

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the input.  I'm still a bit concerned on #2...

BeanIO uses reflection to resolve and create the user-defined bean objects 
bound to stream components in a mapping file.  All classes are resolved when a 
mapping file is initially loaded (before any BeanReader/Writer instance is 
created).

So given that, will the class loader for the bundle that loads a mapping file 
from an input stream (in this case Camel, right?) be able to resolve the user 
defined bean classes in an OSGi environment?
```

Original comment by `kevin.s...@gmail.com` on 6 Feb 2012 at 7:44

**Comment by GoogleCodeExporter** [comment]
```
Ad 2
No that will not work in OSGi. I guess its better to give end-users the 
alternative to provide a ClassLoader instance for you to use for all class 
loading by beanio.

And you would need to declare that beanio uses dynamic imports, so it at 
runtime is allowed to see classes from packages which was *not* on the imported 
list in the MANIFEST.MF of the beanio JAR. Because beanio will as you say based 
on reflection load classes define in XML mapping files from end users.

```

Original comment by `claus.ib...@gmail.com` on 7 Feb 2012 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
I'll update the JAR manifest for release 1.2.3, but leave this issue open until 
the class loader issues can be resolved in the upcoming 2.0 release.

Thanks again for your help!
```

Original comment by `kevin.s...@gmail.com` on 8 Feb 2012 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
OSGi JAR manifest entries added in release 1.2.3.  But this issue will remain 
open until BeanIO accepts a user provided class loader.
```

Original comment by `kevin.s...@gmail.com` on 12 Feb 2012 at 7:54
- Added labels: **Milestone-1.2.3**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the 1.2.3 release. There is some slight errors in the MANIFEST.MF 
file.

I get this exception now in osgi

-------------------------------------------------------------------------------
Test set: org.apache.camel.itest.osgi.beanio.BeanIODataFormatSimpleTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 27.559 sec <<< 
FAILURE!
testMarshal(org.apache.camel.itest.osgi.beanio.BeanIODataFormatSimpleTest)  
Time elapsed: 17.414 sec  <<< ERROR!
org.beanio.BeanIOException: Failed to load stream factory implementation class 
'org.beanio.parser.DefaultStreamFactory'
    at org.beanio.StreamFactory.newInstance(StreamFactory.java:241)
    at org.apache.camel.dataformat.beanio.BeanIODataFormat.doStart(BeanIODataFormat.java:79)
    at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:60)


The code line that fails is:
            factory = StreamFactory.newInstance();

You need to export the org.beanio.parser package as well.

```

Original comment by `claus.ib...@gmail.com` on 22 Feb 2012 at 9:12

**Comment by GoogleCodeExporter** [comment]
```
Okay after a bit I have crafted a MANIFEST.MF file that works with OSGi. You 
have to export all the public packages one by one. So I exported them all, 
except for the util package as I assumed its for internal use.
```

Original comment by `claus.ib...@gmail.com` on 22 Feb 2012 at 9:57

**Comment by GoogleCodeExporter** [comment]
```
The attached manifest.mf file
```

Original comment by `claus.ib...@gmail.com` on 22 Feb 2012 at 9:58

Attachments:
- [MANIFEST.MF](https://storage.googleapis.com/google-code-attachments/beanio/issue-26/comment-9/MANIFEST.MF)

**Comment by GoogleCodeExporter** [comment]
```
Interesting, I was thinking I only had to export BeanIO interfaces, and not 
their implementation.  Thanks again for the help!  And I'll be sure to update 
the manifest in the next release.
```

Original comment by `kevin.s...@gmail.com` on 22 Feb 2012 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
Hi Claus, I've updated the manifest entry to export all packages in the 
2.0.0.M1 release.  If you have a few spare minutes, could you try it out?  If 
it works, I'll make the same change to 1.2.x.  Thanks!
```

Original comment by `kevin.s...@gmail.com` on 5 Mar 2012 at 4:17

**Comment by GoogleCodeExporter** [comment]
```
Yeah let me give it a test spin, when I get a few free cycles.
```

Original comment by `claus.ib...@gmail.com` on 9 Mar 2012 at 10:12

**Comment by GoogleCodeExporter** [comment]
```
I can install the bundle. But when I use it with the current Camel code I get 
this error

testUnmarshal(org.apache.camel.itest.osgi.beanio.BeanIODataFormatSimpleTest)  
Time elapsed: 8.525 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/parsers/ParserConfigurationException
    at org.beanio.internal.config.xml.XmlConfigurationLoader.<init>(XmlConfigurationLoader.java:34)
    at org.beanio.internal.compiler.StreamCompiler.<init>(StreamCompiler.java:47)
    at org.beanio.internal.DefaultStreamFactory.init(DefaultStreamFactory.java:47)
    at org.beanio.StreamFactory.newInstance(StreamFactory.java:287)
    at org.beanio.StreamFactory.newInstance(StreamFactory.java:251)
    at org.apache.camel.dataformat.beanio.BeanIODataFormat.doStart(BeanIODataFormat.java:79)
```

Original comment by `claus.ib...@gmail.com` on 12 Mar 2012 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
You need to have the dynamic import package, in case beanio creates a new 
end-user class when it maps to/from java beans.

DynamicImport-Package: *
```

Original comment by `claus.ib...@gmail.com` on 12 Mar 2012 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
That should also most likely help with the loading of the javax packages. These 
packages can be a bi tricky as there can be different JAXB frameworks installed 
on the JVM container.
```

Original comment by `claus.ib...@gmail.com` on 12 Mar 2012 at 3:39

**Comment by GoogleCodeExporter** [comment]
```
Thanks again Claus.  Hopefully fixed in release 1.2.4, and eventually 2.0.0.M2
```

Original comment by `kevin.s...@gmail.com` on 24 Mar 2012 at 9:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.s...@gmail.com` on 24 Mar 2012 at 9:14
- Added labels: **Milestone-1.2.4**
- Removed labels: **Milestone-1.2.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kevin.s...@gmail.com` on 4 May 2012 at 3:41
- Changed state: **Fixed**
